name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ falconlink.os }}
    strategy:
      falconlink:
        os: [ubuntu-latest] # support for MacOS in the future

    steps:
      - uses: actions/checkout@v3
      # - name: Install dependencies 
      #   run: sh setup.sh
      - name: Build
        run: mkdir build && cd build && cmake ..
